## GPT menggunakan scretch

In [1]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-01-04 13:25:36--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.08s   

2025-01-04 13:25:36 (12.8 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [2]:
# Membuka file 'input.txt' dalam mode baca ('r') dan dengan encoding 'utf-8' untuk memastikan karakter non-ASCII dapat dibaca dengan benar
with open('input.txt', 'r', encoding='utf-8') as f:
    # Membaca seluruh isi file dan menyimpannya dalam variabel 'text'
    text = f.read()


In [3]:
# Menampilkan panjang dataset dalam jumlah karakter
print("length of dataset in characters: ", len(text))


length of dataset in characters:  1115394


In [4]:
# Menampilkan 1000 karakter pertama dari isi dataset
print(text[:1000])


First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [5]:
# Mengambil semua karakter unik yang terdapat dalam teks
chars = sorted(list(set(text)))

# Menentukan jumlah karakter unik (ukuran kosakata)
vocab_size = len(chars)

# Mencetak semua karakter unik yang ada dalam teks
print(''.join(chars))

# Mencetak ukuran kosakata (jumlah karakter unik)
print(vocab_size)



 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [8]:
# Membuat pemetaan dari karakter ke integer
stoi = { ch:i for i,ch in enumerate(chars) }  # Pemetaan dari karakter (ch) ke indeks (i)
itos = { i:ch for i,ch in enumerate(chars) }  # Pemetaan dari indeks (i) ke karakter (ch)

# Membuat fungsi encoder: mengubah string menjadi daftar integer berdasarkan pemetaan
encode = lambda s: [stoi[c] for c in s]  # Menggunakan pemetaan 'stoi' untuk mengonversi setiap karakter menjadi integer

# Membuat fungsi decoder: mengubah daftar integer kembali menjadi string
decode = lambda l: ''.join([itos[i] for i in l])  # Menggunakan pemetaan 'itos' untuk mengonversi setiap integer kembali ke karakter

# Menampilkan hasil konversi string "hii there" menjadi daftar integer
print(encode("kamu sedang menggunakan PyTorch"))

# Menampilkan hasil dekripsi kembali dari daftar integer ke string yang semula
print(decode(encode("kamu sedang menggunakan PyTorch")))


[49, 39, 51, 59, 1, 57, 43, 42, 39, 52, 45, 1, 51, 43, 52, 45, 45, 59, 52, 39, 49, 39, 52, 1, 28, 63, 32, 53, 56, 41, 46]
kamu sedang menggunakan PyTorch


In [7]:
# Mengimpor pustaka PyTorch untuk manipulasi tensor
import torch  # PyTorch digunakan untuk operasi tensor dan komputasi yang efisien

# Mengencode seluruh dataset teks dan mengubahnya menjadi tensor PyTorch
data = torch.tensor(encode(text), dtype=torch.long)  # Mengonversi hasil encode ke tensor PyTorch dengan tipe data 'long'

# Menampilkan dimensi (shape) dan tipe data dari tensor
print(data.shape, data.dtype)

# Menampilkan 1000 elemen pertama dari tensor untuk inspeksi
print(data[:1000])  # Menampilkan 1000 karakter pertama yang telah diencode menjadi bentuk tensor


torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [ ]:
# Membagi data menjadi set pelatihan dan validasi
n = int(0.9*len(data))  # Menentukan indeks pemisahan: 90% data digunakan untuk pelatihan, sisanya untuk validasi

# Menyusun data pelatihan yang mencakup 90% pertama dari data
train_data = data[:n]

# Menyusun data validasi yang mencakup sisanya (10% terakhir) dari data
val_data = data[n:]


In [ ]:
# Menentukan ukuran blok (jumlah karakter dalam satu blok)
block_size = 8

# Menampilkan blok pertama yang berisi 'block_size + 1' karakter dari data pelatihan
train_data[:block_size+1]


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [ ]:
# Membagi data pelatihan menjadi input (x) dan target (y) untuk model
x = train_data[:block_size]  # Mengambil blok pertama data sebagai input (x), berisi 8 karakter pertama
y = train_data[1:block_size+1]  # Mengambil target yang merupakan karakter yang diikuti oleh input, berisi 8 karakter setelah x

# Iterasi melalui setiap posisi dalam blok untuk menampilkan konteks dan target
for t in range(block_size):
    context = x[:t+1]  # Mengambil bagian awal dari input yang berisi konteks hingga posisi t
    target = y[t]  # Target untuk posisi t adalah karakter yang sesuai pada y
    print(f"when input is {context} the target: {target}")


when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [ ]:
# Menetapkan seed untuk kontrol acak agar hasil eksperimen dapat direproduksi
torch.manual_seed(1337)

# Menentukan ukuran batch (berapa banyak urutan independen yang akan diproses secara paralel)
batch_size = 4

# Menentukan ukuran blok (panjang konteks maksimum untuk prediksi)
block_size = 8

# Fungsi untuk mendapatkan batch data
def get_batch(split):
    # Menghasilkan batch kecil data input x dan target y
    # Memilih data pelatihan atau validasi berdasarkan argumen split
    data = train_data if split == 'train' else val_data

    # Menghasilkan indeks acak untuk memulai setiap urutan input dalam batch
    ix = torch.randint(len(data) - block_size, (batch_size,))  # Pastikan urutan tidak melampaui panjang data

    # Membuat tensor input x dari setiap urutan data
    x = torch.stack([data[i:i+block_size] for i in ix])  # Setiap urutan memiliki panjang block_size

    # Membuat tensor target y yang merupakan urutan data yang bergeser satu langkah
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])  # Target y adalah urutan input yang bergeser satu karakter
    return x, y

# Mendapatkan batch pelatihan
xb, yb = get_batch('train')

# Menampilkan bentuk dan isi dari input dan target batch
print('inputs:')
print(xb.shape)  # Menampilkan bentuk (dimensi) dari tensor input
print(xb)  # Menampilkan nilai dari tensor input
print('targets:')
print(yb.shape)  # Menampilkan bentuk (dimensi) dari tensor target
print(yb)  # Menampilkan nilai dari tensor target

print('----')

# Menampilkan input dan target untuk setiap urutan dalam batch
for b in range(batch_size):  # Iterasi untuk setiap batch (urutan input)
    for t in range(block_size):  # Iterasi untuk setiap posisi dalam urutan
        context = xb[b, :t+1]  # Mengambil konteks yang semakin panjang dari input untuk setiap langkah waktu
        target = yb[b,t]  # Menentukan target yang sesuai untuk posisi t dalam urutan
        print(f"when input is {context.tolist()} the target: {target}")


inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53

In [ ]:
# Mencetak tensor input (xb) yang akan digunakan sebagai input untuk transformer
print(xb)  # Menampilkan seluruh tensor input dari batch yang dihasilkan


tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [ ]:
# Mengimpor pustaka PyTorch dan fungsionalitas yang dibutuhkan
import torch
import torch.nn as nn
from torch.nn import functional as F

# Menetapkan seed untuk kontrol acak agar hasil eksperimen dapat direproduksi
torch.manual_seed(1337)

# Definisi kelas model bahasa bigram menggunakan PyTorch
class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # Membuat tabel embedding untuk token. Tabel ini mengasosiasikan setiap token dengan logit untuk token berikutnya.
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)  # Ukuran embedding adalah vocab_size, karena kita memprediksi token berikutnya

    def forward(self, idx, targets=None):
        # idx dan targets adalah tensor (B, T) yang berisi indeks token dalam urutan (dimensi B= batch, T= waktu/urutan)
        logits = self.token_embedding_table(idx)  # (B, T, C), logit untuk setiap token pada setiap posisi waktu

        if targets is None:
            loss = None  # Jika tidak ada target, tidak menghitung loss
        else:
            B, T, C = logits.shape  # Mengambil bentuk dari logits (batch_size, seq_length, vocab_size)
            logits = logits.view(B*T, C)  # Merubah bentuk logits menjadi dua dimensi: (B*T, C)
            targets = targets.view(B*T)  # Merubah target menjadi bentuk (B*T,)
            loss = F.cross_entropy(logits, targets)  # Menghitung loss menggunakan cross entropy

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx adalah tensor (B, T) yang berisi urutan indeks dalam konteks saat ini
        for _ in range(max_new_tokens):
            # Mendapatkan prediksi logit
            logits, loss = self(idx)
            # Fokus pada langkah waktu terakhir
            logits = logits[:, -1, :]  # Hanya ambil logit untuk token terakhir di setiap urutan
            # Terapkan softmax untuk mendapatkan probabilitas
            probs = F.softmax(logits, dim=-1)  # Menghitung distribusi probabilitas untuk token berikutnya
            # Sampling dari distribusi probabilitas
            idx_next = torch.multinomial(probs, num_samples=1)  # Sampling satu token dari distribusi probabilitas
            # Menambahkan token yang disampling ke urutan yang sedang berlangsung
            idx = torch.cat((idx, idx_next), dim=1)  # Menambahkan token baru ke urutan input untuk iterasi berikutnya
        return idx

# Membuat model dengan ukuran kosakata tertentu
m = BigramLanguageModel(vocab_size)

# Menghitung logits dan loss untuk input batch yang diberikan
logits, loss = m(xb, yb)
print(logits.shape)  # Menampilkan bentuk dari tensor logits (B, T, C)
print(loss)  # Menampilkan loss yang dihitung untuk batch

# Men-generate 100 token baru berdasarkan urutan input awal
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


In [ ]:
# Membuat optimizer PyTorch menggunakan AdamW
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)


In [ ]:
# Menetapkan ukuran batch
batch_size = 32

# Melakukan pelatihan selama 100 langkah
for steps in range(100):  # Menambah jumlah langkah untuk hasil yang lebih baik...

    # Mengambil batch data pelatihan
    xb, yb = get_batch('train')  # Mendapatkan batch input dan target dari data pelatihan

    # Mengevaluasi loss (kerugian)
    logits, loss = m(xb, yb)  # Menghitung logits dan loss menggunakan model

    # Mengatur gradien ke nol sebelum backpropagation
    optimizer.zero_grad(set_to_none=True)  # Menghapus gradien sebelumnya agar tidak menumpuk

    # Melakukan backpropagation untuk menghitung gradien
    loss.backward()  # Menghitung gradien berdasarkan loss

    # Memperbarui parameter model berdasarkan gradien
    optimizer.step()  # Melakukan langkah optimasi untuk memperbarui bobot model

# Mencetak nilai loss setelah selesai pelatihan
print(loss.item())  # Menampilkan nilai loss terakhir setelah 100 langkah pelatihan


4.65630578994751


In [ ]:
# Menghasilkan 500 token baru berdasarkan urutan input yang dimulai dari tensor berisi nilai nol
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))



oTo.JUZ!!zqe!
xBP qbs$Gy'AcOmrLwwt
p$x;Seh-onQbfM?OjKbn'NwUAW -Np3fkz$FVwAUEa-wzWC -wQo-R!v -Mj?,SPiTyZ;o-opr$mOiPJEYD-CfigkzD3p3?zvS;ADz;.y?o,ivCuC'zqHxcVT cHA
rT'Fd,SBMZyOslg!NXeF$sBe,juUzLq?w-wzP-h
ERjjxlgJzPbHxf$ q,q,KCDCU fqBOQT
SV&CW:xSVwZv'DG'NSPypDhKStKzC -$hslxIVzoivnp ,ethA:NCCGoi
tN!ljjP3fwJMwNelgUzzPGJlgihJ!d?q.d
pSPYgCuCJrIFtb
jQXg
pA.P LP,SPJi
DBcuBM:CixjJ$Jzkq,OLf3KLQLMGph$O 3DfiPHnXKuHMlyjxEiyZib3FaHV-oJa!zoc'XSP :CKGUhd?lgCOF$;;DTHZMlvvcmZAm;:iv'MMgO&Ywbc;BLCUd&vZINLIzkuTGZa
D.?


## The mathematical trick in self-attention

In [ ]:
# Menetapkan seed untuk kontrol acak agar hasil eksperimen dapat direproduksi
torch.manual_seed(42)

# Membuat matriks bawah segitiga (lower triangular matrix) berukuran 3x3 yang diisi dengan angka 1
a = torch.tril(torch.ones(3, 3))

# Menormalkan setiap baris dari matriks 'a' sehingga jumlah elemen dalam setiap baris menjadi 1
a = a / torch.sum(a, 1, keepdim=True)

# Membuat matriks acak 'b' berukuran 3x2 dengan nilai antara 0 dan 10
b = torch.randint(0, 10, (3, 2)).float()

# Melakukan perkalian matriks antara 'a' dan 'b'
c = a @ b

# Menampilkan matriks 'a'
print('a=')
print(a)

# Menampilkan matriks pemisah
print('--')

# Menampilkan matriks 'b'
print('b=')
print(b)

# Menampilkan hasil perkalian matriks 'a' dan 'b' dalam matriks 'c'
print('--')
print('c=')
print(c)


a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# Menetapkan seed untuk kontrol acak agar hasil eksperimen dapat direproduksi
torch.manual_seed(1337)

# Menentukan dimensi tensor untuk batch, waktu (time steps), dan saluran (channels)
B, T, C = 4, 8, 2  # B = batch size, T = time steps, C = number of channels

# Membuat tensor acak berukuran (B, T, C) yang berisi data dengan distribusi normal
x = torch.randn(B, T, C)

# Menampilkan bentuk tensor x
x.shape


torch.Size([4, 8, 2])

In [ ]:
# Membuat tensor kosong 'xbow' yang berukuran (B, T, C) untuk menampung hasil perhitungan rata-rata
xbow = torch.zeros((B, T, C))

# Iterasi untuk setiap batch (b) dan setiap langkah waktu (t)
for b in range(B):
    for t in range(T):
        # Mengambil elemen dari tensor x untuk batch b dan langkah waktu hingga t
        xprev = x[b, :t+1]  # (t+1, C), memilih semua langkah waktu hingga t untuk batch b

        # Menghitung rata-rata sepanjang dimensi waktu (t) untuk batch b dan langkah waktu t
        xbow[b, t] = torch.mean(xprev, 0)  # Mengambil rata-rata sepanjang dimensi waktu (t) untuk setiap saluran (C)


In [ ]:
# Membuat matriks bobot 'wei' berbentuk segitiga bawah (lower triangular matrix) dengan dimensi T x T
wei = torch.tril(torch.ones(T, T))  # Membuat matriks segitiga bawah yang diisi dengan angka 1

# Menormalkan setiap baris matriks 'wei' agar jumlah elemen dalam setiap baris menjadi 1
wei = wei / wei.sum(1, keepdim=True)  # Normalisasi sehingga jumlah setiap baris adalah 1

# Melakukan perkalian matriks antara 'wei' (T, T) dan 'x' (B, T, C)
xbow2 = wei @ x  # Perkalian matriks: (T, T) @ (B, T, C) ---> (B, T, C)

# Memeriksa apakah hasil dari perkalian matriks sama dengan hasil sebelumnya 'xbow'
torch.allclose(xbow, xbow2)  # Memeriksa apakah 'xbow' dan 'xbow2' hampir identik (mendekati sama dalam nilai)


True

In [ ]:
# Membuat matriks segitiga bawah (lower triangular matrix) dengan ukuran T x T
tril = torch.tril(torch.ones(T, T))  # Membuat matriks segitiga bawah dengan elemen 1 di bawah diagonal dan 0 di atas diagonal

# Membuat matriks bobot 'wei' yang berukuran T x T dan menginisialisasinya dengan nol
wei = torch.zeros((T, T))

# Mengisi elemen di atas diagonal dengan nilai negatif tak hingga (-inf) untuk mask
wei = wei.masked_fill(tril == 0, float('-inf'))  # Menandai elemen yang tidak ada di segitiga bawah dengan -inf

# Menghitung Softmax dari matriks bobot 'wei' sepanjang dimensi waktu (dim=-1) untuk normalisasi
wei = F.softmax(wei, dim=-1)  # Softmax digunakan untuk mengonversi nilai ke probabilitas dengan memastikan jumlah barisnya adalah 1

# Melakukan perkalian matriks antara 'wei' dan 'x' untuk mendapatkan hasil agregasi berbobot
xbow3 = wei @ x  # Perkalian matriks: (T, T) @ (B, T, C) ---> (B, T, C)

# Memeriksa apakah hasil perhitungan menggunakan Softmax hampir sama dengan hasil perhitungan sebelumnya 'xbow'
torch.allclose(xbow, xbow3)  # Memeriksa apakah 'xbow' dan 'xbow3' hampir identik (mendekati sama dalam nilai)


True

In [ ]:
# Menetapkan seed untuk kontrol acak agar hasil eksperimen dapat direproduksi
torch.manual_seed(1337)

# Menentukan dimensi tensor untuk batch, waktu (time steps), dan saluran (channels)
B, T, C = 4, 8, 32  # B = batch size, T = time steps, C = number of channels

# Membuat tensor acak 'x' dengan ukuran (B, T, C) yang berisi data dengan distribusi normal
x = torch.randn(B, T, C)

# Menentukan ukuran untuk setiap kepala dalam mekanisme self-attention
head_size = 16

# Membuat lapisan Linear untuk key, query, dan value
key = nn.Linear(C, head_size, bias=False)  # Mengubah tensor input menjadi key dengan dimensi 'head_size'
query = nn.Linear(C, head_size, bias=False)  # Mengubah tensor input menjadi query dengan dimensi 'head_size'
value = nn.Linear(C, head_size, bias=False)  # Mengubah tensor input menjadi value dengan dimensi 'head_size'

# Menghitung key, query, dan value untuk input x
k = key(x)   # (B, T, head_size) ---> (B, T, 16)
q = query(x) # (B, T, head_size) ---> (B, T, 16)

# Menghitung matriks bobot perhatian (attention weights) menggunakan produk titik antara query dan key
wei =  q @ k.transpose(-2, -1) # (B, T, head_size) @ (B, head_size, T) ---> (B, T, T)

# Membuat matriks segitiga bawah (lower triangular matrix) untuk mask
tril = torch.tril(torch.ones(T, T))  # Membuat matriks segitiga bawah berukuran T x T yang diisi dengan angka 1

# Masking nilai di atas diagonal agar tidak dipertimbangkan dalam perhatian
wei = wei.masked_fill(tril == 0, float('-inf'))  # Menandai elemen di atas diagonal dengan -inf

# Menghitung softmax dari bobot perhatian untuk mendapatkan distribusi probabilitas
wei = F.softmax(wei, dim=-1)  # Softmax memastikan jumlah setiap baris adalah 1

# Menghitung output dengan menggunakan bobot perhatian untuk menggabungkan value
v = value(x)  # (B, T, head_size)
out = wei @ v  # Perkalian matriks antara bobot perhatian 'wei' dan value 'v'

# Menampilkan bentuk tensor output dari self-attention
out.shape  # Memeriksa bentuk tensor output yang dihasilkan oleh self-attention


torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
# Membuat tensor acak untuk key dan query dengan ukuran (B, T, head_size)
k = torch.randn(B, T, head_size)  # Key tensor dengan dimensi (B, T, head_size)
q = torch.randn(B, T, head_size)  # Query tensor dengan dimensi (B, T, head_size)

# Menghitung matriks bobot perhatian (attention weights) antara query dan key
wei = q @ k.transpose(-2, -1) * head_size**-0.5


In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # menyesuaikan tingkat ketajaman distribusi.

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d:  # Class ini adalah implementasi dari Layer Normalization 1D (sebelumnya BatchNorm1d)

    def __init__(self, dim, eps=1e-5, momentum=0.1):
        self.eps = eps  # epsilon untuk stabilitas numerik, mencegah pembagian dengan nol
        self.gamma = torch.ones(dim)  # Gamma adalah parameter skala (scale), diinisialisasi dengan 1
        self.beta = torch.zeros(dim)  # Beta adalah parameter pergeseran (shift), diinisialisasi dengan 0

    def __call__(self, x):
        # Melakukan perhitungan untuk forward pass
        xmean = x.mean(1, keepdim=True)  # Menghitung rata-rata batch (mean) sepanjang dimensi 1 (dimensi fitur)
        xvar = x.var(1, keepdim=True)    # Menghitung varians batch (variance) sepanjang dimensi 1
        xhat = (x - xmean) / torch.sqrt(xvar + self.eps)  # Normalisasi, mengurangi mean dan membagi dengan deviasi standar
        self.out = self.gamma * xhat + self.beta  # Menambahkan skala (gamma) dan pergeseran (beta) ke hasil normalisasi
        return self.out  # Mengembalikan output yang sudah dinormalisasi dan ditransformasi

    def parameters(self):
        return [self.gamma, self.beta]  # Mengembalikan parameter model (gamma dan beta)

# Menetapkan seed untuk kontrol acak agar eksperimen dapat direproduksi
torch.manual_seed(1337)

# Membuat instance dari LayerNorm1d dengan dimensi fitur 100
module = LayerNorm1d(100)

# Membuat tensor acak dengan ukuran batch 32 dan 100 dimensi untuk setiap vektor
x = torch.randn(32, 100)

# Mengaplikasikan LayerNorm1d pada tensor x
x = module(x)

# Menampilkan bentuk tensor output setelah normalisasi
x.shape


torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std()  # Menghitung mean dan standar deviasi untuk fitur pertama (kolom pertama) di seluruh input batch


(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std()  # Menghitung mean dan standar deviasi untuk fitur dari satu input di dalam batch


(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference



In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# Hyperparameters
batch_size = 16 # Banyaknya urutan yang diproses secara paralel
block_size = 32 # Panjang konteks maksimum untuk prediksi
max_iters = 5000 # Jumlah iterasi pelatihan maksimal
eval_interval = 100 # Interval evaluasi setiap berapa iterasi
learning_rate = 1e-3 # Laju pembelajaran
device = 'cuda' if torch.cuda.is_available() else 'cpu' # Menentukan perangkat (GPU jika tersedia)
eval_iters = 200 # Jumlah iterasi untuk evaluasi
n_embd = 64 # Dimensi embedding untuk token dan posisi
n_head = 4 # Jumlah kepala dalam multi-head attention
n_layer = 4 # Jumlah layer Transformer
dropout = 0.0 # Tingkat dropout (regularisasi)

# ------------

# Menetapkan seed untuk memastikan eksperimen yang dapat direproduksi
torch.manual_seed(1337)

# Membaca teks dari file input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# Menyusun semua karakter unik dalam teks
chars = sorted(list(set(text))) # Set untuk menghapus duplikasi, di-sort
vocab_size = len(chars) # Ukuran kosakata, jumlah karakter unik dalam teks

# Membuat pemetaan dari karakter ke integer dan sebaliknya
stoi = { ch:i for i,ch in enumerate(chars) } # String ke integer
itos = { i:ch for i,ch in enumerate(chars) } # Integer ke string

# Fungsi encoder dan decoder
encode = lambda s: [stoi[c] for c in s] # Mengubah string menjadi daftar indeks integer
decode = lambda l: ''.join([itos[i] for i in l]) # Mengubah daftar indeks integer kembali menjadi string

# Membagi data menjadi data pelatihan dan validasi
data = torch.tensor(encode(text), dtype=torch.long) # Mengubah teks menjadi tensor
n = int(0.9*len(data)) # 90% data untuk pelatihan
train_data = data[:n] # Data pelatihan
val_data = data[n:] # Data validasi

# Fungsi untuk mengambil batch data
def get_batch(split):
    data = train_data if split == 'train' else val_data # Memilih data sesuai split (train/val)
    ix = torch.randint(len(data) - block_size, (batch_size,)) # Menghasilkan indeks acak untuk batch
    x = torch.stack([data[i:i+block_size] for i in ix]) # Ambil batch input (ukuran batch x block_size)
    y = torch.stack([data[i+1:i+block_size+1] for i in ix]) # Ambil target yang bergeser 1 langkah dari x
    x, y = x.to(device), y.to(device) # Memindahkan batch ke perangkat (GPU/CPU)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval() # Menetapkan model ke mode evaluasi
    for split in ['train', 'val']: # Evaluasi pada data train dan val
        losses = torch.zeros(eval_iters) # Membuat tensor kosong untuk menyimpan loss
        for k in range(eval_iters):
            X, Y = get_batch(split) # Mengambil batch untuk evaluasi
            logits, loss = model(X, Y) # Menghitung logits dan loss
            losses[k] = loss.item() # Menyimpan loss
        out[split] = losses.mean() # Menghitung rata-rata loss
    model.train() # Mengembalikan model ke mode pelatihan
    return out

# Head (Self-Attention)
class Head(nn.Module):
    """Satu kepala self-attention"""
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False) # Layer untuk key
        self.query = nn.Linear(n_embd, head_size, bias=False) # Layer untuk query
        self.value = nn.Linear(n_embd, head_size, bias=False) # Layer untuk value
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size))) # Matriks segitiga bawah untuk masking
        self.dropout = nn.Dropout(dropout) # Dropout untuk regularisasi

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)   # Menghitung key
        q = self.query(x) # Menghitung query
        # Menghitung skor perhatian (affinities)
        wei = q @ k.transpose(-2,-1) * C**-0.5 # Produk titik antara query dan key
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # Masking dengan matriks segitiga bawah
        wei = F.softmax(wei, dim=-1) # Softmax untuk mendapatkan distribusi probabilitas
        wei = self.dropout(wei) # Dropout pada bobot perhatian
        # Agregasi berbobot nilai-nilai
        v = self.value(x) # Menghitung value
        out = wei @ v # Perkalian matriks antara bobot perhatian dan value
        return out

# MultiHeadAttention (Beberapa Kepala Self-Attention)
class MultiHeadAttention(nn.Module):
    """Beberapa kepala self-attention secara paralel"""
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)]) # Membuat beberapa kepala
        self.proj = nn.Linear(n_embd, n_embd) # Proyeksi hasil dari semua kepala
        self.dropout = nn.Dropout(dropout) # Dropout untuk regularisasi

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1) # Menggabungkan output dari semua kepala
        out = self.dropout(self.proj(out)) # Proyeksi dan dropout
        return out

# FeedForward (Layer Linear dengan Aktivasi Non-Linear)
class FeedFoward(nn.Module):
    """Layer linear yang diikuti dengan non-linearitas"""
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd), # Mengubah dimensi menjadi 4 kali lipat
            nn.ReLU(), # Fungsi aktivasi ReLU
            nn.Linear(4 * n_embd, n_embd), # Mengembalikan dimensi ke n_embd
            nn.Dropout(dropout), # Dropout untuk regularisasi
        )

    def forward(self, x):
        return self.net(x) # Forward pass melalui jaringan

# Block Transformer
class Block(nn.Module):
    """Block Transformer: komunikasi diikuti dengan komputasi"""
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head # Menentukan ukuran setiap kepala
        self.sa = MultiHeadAttention(n_head, head_size) # Multi-head attention
        self.ffwd = FeedFoward(n_embd) # Feedforward
        self.ln1 = nn.LayerNorm(n_embd) # Normalisasi layer pertama
        self.ln2 = nn.LayerNorm(n_embd) # Normalisasi layer kedua

    def forward(self, x):
        x = x + self.sa(self.ln1(x)) # Residual connection setelah self-attention
        x = x + self.ffwd(self.ln2(x)) # Residual connection setelah feedforward
        return x

# Bigram Language Model menggunakan Transformer
class BigramLanguageModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd) # Tabel embedding untuk token
        self.position_embedding_table = nn.Embedding(block_size, n_embd) # Tabel embedding untuk posisi
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)]) # Beberapa blok Transformer
        self.ln_f = nn.LayerNorm(n_embd) # Layer normalisasi terakhir
        self.lm_head = nn.Linear(n_embd, vocab_size) # Layer untuk memetakan kembali ke kosakata

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx) # Mendapatkan embedding untuk token
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # Mendapatkan embedding untuk posisi
        x = tok_emb + pos_emb # Menambahkan embedding token dan posisi
        x = self.blocks(x) # Melalui blok Transformer
        x = self.ln_f(x) # Layer normalisasi terakhir
        logits = self.lm_head(x) # Mendapatkan logits

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C) # Merubah bentuk untuk cross-entropy loss
            targets = targets.view(B*T) # Merubah bentuk target
            loss = F.cross_entropy(logits, targets) # Menghitung loss

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:] # Mengambil hanya block_size token terakhir
            logits, loss = self(idx_cond) # Mendapatkan prediksi
            logits = logits[:, -1, :] # Fokus pada prediksi untuk token terakhir
            probs = F.softmax(logits, dim=-1) # Softmax untuk probabilitas
            idx_next = torch.multinomial(probs, num_samples=1) # Sampling token berikutnya
            idx = torch.cat((idx, idx_next), dim=1) # Menambahkan token baru ke urutan
        return idx

model = BigramLanguageModel()
m = model.to(device)
# Menampilkan jumlah parameter dalam model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# Membuat optimizer PyTorch
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss() # Evaluasi loss
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # Mengambil batch data pelatihan
    xb, yb = get_batch('train')

    # Menghitung loss dan memperbarui parameter model
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# Menghasilkan teks dari model
context = torch.zeros((1, 1), dtype=torch.long, device=device) # Mulai dengan konteks kosong
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist())) # Menghasilkan 2000 token


0.209729 M parameters
step 0: train loss 4.4116, val loss 4.4022
step 100: train loss 2.6568, val loss 2.6670
step 200: train loss 2.5090, val loss 2.5058
step 300: train loss 2.4198, val loss 2.4340
step 400: train loss 2.3503, val loss 2.3567
step 500: train loss 2.2970, val loss 2.3136
step 600: train loss 2.2410, val loss 2.2506
step 700: train loss 2.2062, val loss 2.2198
step 800: train loss 2.1638, val loss 2.1871
step 900: train loss 2.1232, val loss 2.1494
step 1000: train loss 2.1020, val loss 2.1293
step 1100: train loss 2.0704, val loss 2.1196
step 1200: train loss 2.0382, val loss 2.0798
step 1300: train loss 2.0249, val loss 2.0640
step 1400: train loss 1.9922, val loss 2.0354
step 1500: train loss 1.9707, val loss 2.0308
step 1600: train loss 1.9614, val loss 2.0474
step 1700: train loss 1.9393, val loss 2.0130
step 1800: train loss 1.9070, val loss 1.9943
step 1900: train loss 1.9057, val loss 1.9871
step 2000: train loss 1.8834, val loss 1.9954
step 2100: train loss 1.